version: "3.9"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./imports/realm-export.json:/opt/keycloak/data/import/realm-export.json
    environment:
      KEYCLOAK_ADMIN: "admin"
      KEYCLOAK_ADMIN_PASSWORD: "admin"
    command: "start-dev --import-realm  --health-enabled=true"
    ports:
      - "8080:8080"
  echo-server:
    container_name: echo-server
    image: skylove/vodafoneziggo_security:latest
    ports:
      - "8081:8081"
    depends_on:
      keycloak:
        condition: service_healthy
    restart: unless-stopped
