version: "3.9"

services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./imports/realm-export.json:/opt/keycloak/imports/realm-export.json
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      KC_HEALTH_ENABLED: true
    profiles:
      - start-dev
    command: "import --file /opt/keycloak/imports/realm-export.json "
    ports:
      - "8080:8080"
  echo-server:
    container_name: echo-server
    image: skylove/vodafoneziggo_security:latest
    ports:
      - "8081:8081"
    depends_on:
      - keycloak
    links:
      - keycloak

